export const productsBurley = [
  {
    id: 1,
    image: require("./images/Lemon-Drops.jpg"),
    name: "Lemon Drops",
    nameTranslation: "(лимонні льодяники)",
    price: 250,
  },
  {
    id: 2,
    image: require("./images/Behemoth.jpg"),
    name: "Behemoth",
    nameTranslation: "(чай з бергамотом)",
    price: 250,
  },
  {
    id: 3,
    image: require("./images/Monomango.jpg"),
    name: "Monomango",
    nameTranslation: "(хвойний манго)",
    price: 250,
  },
  {
    id: 4,
    image: require("./images/Old-Cherry.jpg"),
    name: "Old Cherry",
    nameTranslation: "(стигла вишня )",
    price: 250,
  },
  {
    id: 5,
    image: require("./images/Spicy-Cola.jpg"),
    name: "Spicy Cola",
    nameTranslation: "(кола  зі спеціями)",
    price: 250,
  },
  {
    id: 6,
    image: require("./images/Citron.jpg"),
    name: "Citron",
    nameTranslation: "(цитрус)",
    price: 250,
  },
  {
    id: 7,
    image: require("./images/Ice-Apple.jpg"),
    name: "Ice Apple",
    nameTranslation: "(айс яблуко)",
    price: 250,
  },
  {
    id: 8,
    image: require("./images/Blueberry-Mint.jpg"),
    name: "Blueberry Mint",
    nameTranslation: "(чорниця-мя'та)",
    price: 250,
  },
  {
    id: 9,
    image: require("./images/Cactus-Lime.jpg"),
    name: "Cactus Lime",
    nameTranslation: "(кактус лайм)",
    price: 250,
  },
];
